name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00
  workflow_dispatch: # on button click

jobs:
  sync:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: spf13
          base: main
          head: main
